name: pfeapp
description: application du projet de fin d&#x27;etude


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  flutter_progress_hud: ^1.0.2
  carousel_pro: ^1.0.0
  google_sign_in: ^4.4.6
  shared_preferences: ^0.5.7+2
  fluttertoast: ^4.0.0
  firebase_database: ^3.1.5
  image_picker: ^0.6.7
  carousel_slider: ^2.1.0
  font_awesome_flutter: ^8.8.1
  animated_splash: ^1.0.0

  custom_splash: ^0.0.2











dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/
    - images/cats/
    - images/products/
    - images/brands/


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf



